package com.testproject.sample;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class sample implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "SAMPLE_ID_GENERATOR")
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(sequenceName = "SAMPLE_ID_SEQ", name = "SAMPLE_ID_GENERATOR")
	private java.lang.Long id;

	@org.kie.api.definition.type.Label(value = "name")
	private java.lang.String name;

	@org.kie.api.definition.type.Label(value = "status")
	private java.lang.Boolean status;

	public sample() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.Boolean getStatus() {
		return this.status;
	}

	public void setStatus(java.lang.Boolean status) {
		this.status = status;
	}

	public sample(java.lang.Long id, java.lang.String name,
			java.lang.Boolean status) {
		this.id = id;
		this.name = name;
		this.status = status;
	}

}